# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import game_pb2 as game__pb2


class GameServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetInfoUser = channel.unary_unary(
                '/game.GameService/GetInfoUser',
                request_serializer=game__pb2.Empty.SerializeToString,
                response_deserializer=game__pb2.UserInfo.FromString,
                )
        self.GetCardList = channel.unary_unary(
                '/game.GameService/GetCardList',
                request_serializer=game__pb2.Empty.SerializeToString,
                response_deserializer=game__pb2.CardList.FromString,
                )
        self.GetUserList = channel.unary_unary(
                '/game.GameService/GetUserList',
                request_serializer=game__pb2.Empty.SerializeToString,
                response_deserializer=game__pb2.UserList.FromString,
                )
        self.BuyCard = channel.unary_unary(
                '/game.GameService/BuyCard',
                request_serializer=game__pb2.IdCard.SerializeToString,
                response_deserializer=game__pb2.CardBought.FromString,
                )
        self.SellCard = channel.unary_unary(
                '/game.GameService/SellCard',
                request_serializer=game__pb2.IdCard.SerializeToString,
                response_deserializer=game__pb2.CardSold.FromString,
                )


class GameServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetInfoUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCardList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BuyCard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SellCard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GameServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetInfoUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInfoUser,
                    request_deserializer=game__pb2.Empty.FromString,
                    response_serializer=game__pb2.UserInfo.SerializeToString,
            ),
            'GetCardList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCardList,
                    request_deserializer=game__pb2.Empty.FromString,
                    response_serializer=game__pb2.CardList.SerializeToString,
            ),
            'GetUserList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserList,
                    request_deserializer=game__pb2.Empty.FromString,
                    response_serializer=game__pb2.UserList.SerializeToString,
            ),
            'BuyCard': grpc.unary_unary_rpc_method_handler(
                    servicer.BuyCard,
                    request_deserializer=game__pb2.IdCard.FromString,
                    response_serializer=game__pb2.CardBought.SerializeToString,
            ),
            'SellCard': grpc.unary_unary_rpc_method_handler(
                    servicer.SellCard,
                    request_deserializer=game__pb2.IdCard.FromString,
                    response_serializer=game__pb2.CardSold.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'game.GameService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GameService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetInfoUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/game.GameService/GetInfoUser',
            game__pb2.Empty.SerializeToString,
            game__pb2.UserInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCardList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/game.GameService/GetCardList',
            game__pb2.Empty.SerializeToString,
            game__pb2.CardList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUserList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/game.GameService/GetUserList',
            game__pb2.Empty.SerializeToString,
            game__pb2.UserList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BuyCard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/game.GameService/BuyCard',
            game__pb2.IdCard.SerializeToString,
            game__pb2.CardBought.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SellCard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/game.GameService/SellCard',
            game__pb2.IdCard.SerializeToString,
            game__pb2.CardSold.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
